Ques-1

In [1]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


Ques-2

In [8]:
l1=[]
print("Enter five elements for list one:")
for i in range(5):
    ele=int(input())
    l1.append(ele)
print(l1) 
l2=[]
print("Enter five elements for second list:")
for i in range(5):
    ele=int(input())
    l2.append(ele)
print(l2)    
arr1=np.array(l1)
arr2=np.array(l2)
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)
print(np.sort(arr))

Enter five elements for list one:
12
34
12
45
75
[12, 34, 12, 45, 75]
Enter five elements for second list:
23
11
01
09
65
[23, 11, 1, 9, 65]
[12 34 12 45 75 23 11  1  9 65]
[ 1  9 11 12 12 23 34 45 65 75]


Ques-3

In [14]:
arr=np.arange(1,13).reshape(3,4)
print(arr)
print(np.shape(arr))
print(arr.ndim)
print(arr.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
12


Ques-4

In [18]:
import numpy as np 


arr = np.array( [1,5,4,2,9] ) 
print(arr.shape)
print(arr) 
arr_2D = arr[np.newaxis] 

print(arr_2D.shape)
print(arr_2D)


x = np.zeros((1))
print(x.shape)
print(x)
y = np.expand_dims(x, axis=1)
print(y.shape) 
print(y)


(5,)
[1 5 4 2 9]
(1, 5)
[[1 5 4 2 9]]
(1,)
[0.]
(1, 1)
[[0.]]


Ques-5

In [27]:
arr1=np.arange(4*4).reshape(4,4)
print(arr1)
arr2 = np.array( [ [16,17,18,19] , [20,21,22,23] , [24,25,26,27] , [28,29,30,31] ] )
print(arr2)
ver_stack=np.vstack((arr1,arr2))
print(ver_stack)
hor_stack=np.hstack((arr1,arr2))
print(hor_stack)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  1  2  3 16 17 18 19]
 [ 4  5  6  7 20 21 22 23]
 [ 8  9 10 11 24 25 26 27]
 [12 13 14 15 28 29 30 31]]


Ques-6

In [30]:
import numpy as np
arr = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Original array:")
print(arr)
unique_elements, counts_elements = np.unique(arr, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))


Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]
